baseURL = 'https://Omen-og-or.com/'
languageCode = 'en-us'
title = 'SammyMail | Email Technology Insights'
theme = 'PaperMod'

# Site identity
description = 'Expert insights on email technology, deliverability, and authentication'

# Author information (old format - keeping for backward compatibility)
[author]
  name = 'Sammy'
  email = 'contact@sammymail.com'
  bio = 'Email technology expert and consultant'
  avatar = '/images/avatar.jpg'  # Add your avatar image to static/images/avatar.jpg

[params.author]
  name = 'Sammy'
  email = 'contact@sammymail.com'
  bio = 'Email technology expert and consultant'
  avatar = '/images/avatar.jpg'

# Site settings
[pagination]
  pagerSize = 10

# Enable features
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ['taxonomy', 'term']
canonifyURLs = true

# Image processing
[imaging]
  quality = 80
  resampleFilter = 'CatmullRom'
  anchor = 'smart'
  
[mediaTypes]
  [mediaTypes.'image/webp']
    suffixes = ['webp']
  
[outputFormats]
  [outputFormats.WebP]
    mediaType = 'image/webp'
    isPlainText = false
    isHTMLDocument = false
    permalinkable = false
    weight = 100

# Build settings
buildDrafts = false
buildFuture = false
buildExpired = false

# Markup settings
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
  
  [markup.goldmark.renderer]
    unsafe = true
    
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[params]
  # Theme settings
  theme = 'auto'  # auto, light, dark
  defaultTheme = 'light'  # Default theme for auto mode
  homeInfoParams = { Title = "Email Technology Expert", Content = "Insights, tutorials, and best practices for email technology professionals" }
  
  # Social links
  [params.social]
    twitter = 'https://twitter.com/sammymail'
    github = 'https://github.com/sammymail'
    linkedin = 'https://linkedin.com/company/sammymail'
    email = 'contact@sammymail.com'
    
  # SEO settings
  [params.seo]
    twitter = '@sammymail'
    opengraph = true
    schema = true
    
  # Comments (uncomment and configure as needed)
  # [params.comments]
  #   enabled = true
  #   provider = 'disqus'  # or 'utterances', 'giscus', etc.
  #   disqusShortname = 'your-disqus-shortname'
  
  # Newsletter configuration
  [params.newsletter]
    enable = true
    provider = 'mailchimp'  # or 'convertkit', 'revue', etc.
    mailchimpAction = 'https://your-mailchimp-form-action'
    mailchimpName = 'YOUR_MAILCHIMP_FORM_NAME'
    
  # Table of contents
  [params.toc]
    enable = true
    number = true
    auto = true
    keepStatic = false
    
  # Related content
  [params.related]
    enable = true
    threshold = 80
    includeNewer = true
    toLower = false
  
  # Display settings
  ShowReadingTime = true
  ShowWordCount = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNums = true
  
  # Post navigation
  [params.postNavigation]
    enable = true
    prevText = 'Previous'
    nextText = 'Next'
    
  # Analytics
  [params.analytics]
    enable = false
    googleAnalytics = 'UA-XXXXX-X'  # Your Google Analytics ID
    plausibleAnalytics = ''  # Your Plausible domain
    
  # Search configuration
  [params.search]
    enable = true
    type = 'fusejs'  # or 'algolia', 'lunr'
    contentLocation = 'content/'
    fuseJsOptions = '{ "keys": ["title", "summary", "content"] }'
    
  # Custom CSS/JS
  customCSS = ['css/custom.css']
  customJS = ['js/custom.js']
  
  # Extensions
  [params.extensions]
    mermaid = true  # Enable Mermaid.js for diagrams
    katex = true    # Enable KaTeX for math typesetting
    lazySizes = true # Enable lazy loading for images
  ShowBreadCrumbs = true
  
  # SEO settings
  description = 'Expert insights on email technologies, deliverability, and best practices for developers and marketers'
  keywords = ['email technology', 'email deliverability', 'email marketing', 'SPF', 'DKIM', 'DMARC', 'email development']
  
  # Author information
  author = 'Samuel Omenogor'
  author_image = '/images/author.jpg'
  author_description = 'Email Technology Expert | Deliverability Specialist | Speaker'
  
  # Social links
  socialIcons = [
    { name = 'github', url = 'https://github.com/Omenogor01' },
    { name = 'linkedin', url = 'https://www.linkedin.com/in/samuel-omenogor-a8514125a/' },
    { name = 'envelope', url = 'mailto:samuel@Omen-og-or.com' }
  ]
  
  # Custom CSS
  customCSS = ['css/custom.css']
  
  # Analytics
  googleAnalytics = 'G-D1FJRJDPGC'
  # plausibleAnalytics = 'your-domain.com'
  
  # Comments (uncomment and configure as needed)
  # [params.comments]
  #   enabled = true
  #   provider = 'disqus'
  #   disqusShortname = 'your-disqus-shortname'
  
  # Newsletter (uncomment and configure as needed)
  # [params.newsletter]
  #   enable = true
  #   title = 'Subscribe to our newsletter'
  #   description = 'Get the latest posts delivered right to your inbox.'
  #   endpoint = 'your-newsletter-endpoint'
  
  # Custom scripts
  customJS = ['js/custom.js']
  
  # Theme colors
  [params.colors]
    theme = '#2563EB'  # Primary blue
    link = '#1D4ED8'  # Darker blue for links
    linkHover = '#1E40AF'  # Even darker blue for hover
    background = '#FFFFFF'  # White background
    text = '#1F2937'  # Dark gray text
    textLight = '#6B7280'  # Lighter gray for secondary text
    border = '#E5E7EB'  # Light gray for borders

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2
  
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 3
  
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 4
